tap "hashicorp/tap"
tap "jesseduffield/lazygit"

brew "hashicorp/tap/terraform"
brew "trash"
brew "neovim"
brew "ripgrep"
brew "nvm"
brew "python"
brew "rbenv"
brew "direnv"
brew "git"
brew "jesseduffield/lazygit/lazygit"
brew "tig"
brew "thefuck"
brew "saml2aws"
brew "bundler-completion" 
brew "docker-completion"
brew "gem-completion"
brew "launchctl-completion"
brew "pip-completion"
brew "rails-completion"
brew "rake-completion"
brew "ruby-completion"
brew "rustc-completion"
brew "tmuxinator"
brew "tmuxinator-completion"
brew "rustup"

cask "iterm2"
cask "amethyst"
cask "font-meslo-lg-nerd-font"
cask "ghostty"

