#!/usr/bin/env bash

if ! command -v brew &>/dev/null; then
  echo "installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Running brew bundle..."
brew bundle

echo "Creating symlinks..."
cd ./dotfiles/
stow --target="$HOME" *
cd -

if ! command -v rustup &>/dev/null; then
  echo "Installing Rust..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  source "$HOME/.cargo/env"
else
  echo "Updating Rust..."
  rustup update
fi

if ! command -v nu &>/dev/null; then
  echo "Installing Cargo binaries..."
  bash ./cargo_installs.sh
fi

if ! command -v run_erl &>/dev/null; then
  echo "Installing erlang asdf plugin..."
  asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
fi

if ! command -v mix &>/dev/null; then
  echo "Installing elixir asdf plugin..."
  asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
fi

echo "Installation complete. Please remember to configure the font 'MesloLGS Nerd Font Mono' in your terminal profile."
