#!/usr/bin/env bash

project='name'
group='' # Don't forget the trailing '/' here!
folder="$HOME/dev/$group$project"

tmux has-session -t "$project"

if [ $? != 0 ]; then
	tmux new-session -s "$project" -n editor -d
	tmux send-keys -t "$project" 'cd ~/dev/kiss-the-planet/axum/kiss-the-planet-blog' C-m
	tmux send-keys -t "$project" 'hx .' C-m

	tmux split-window -v -t "$project"
	tmux select-layout -t "$project" main-vertical
	tmux send-keys -t "$project":1.2 'cd ~/dev/kiss-the-planet/axum/kiss-the-planet-blog' C-m
	tmux send-keys -t "$project":1.2 "cargo watch -x 'shuttle run'" C-m

	tmux new-window -n 'shell' -t "$project"
	tmux send-keys -t "$project" 'cd ~/dev/kiss-the-planet/axum/kiss-the-planet-blog' C-m

	tmux select-window -t "$project":editor
	tmux select-pane -t "$project":editor.left
fi
tmux a -t "$project"
